### ISSUE TITLE
Jupyter container exits with "/notebooks/.datacube.conf: Permission denied"

### ISSUE THREAD

**Issue by ikselven** [opendatacube/docker-images#17]
**Steps to reproduce:**
- clone the repository
- cd into `jupyter`
- run `sudo docker-compose up`

**Expected Result:**
There are two containers running, one for PostgreSQL and one for Jupyter, exposing port 8888

**Actual Result:**
The PostgreSQL container runs, but the Jupyter container has exited:
```
jupyter_1   | /usr/local/bin/docker-entrypoint.sh: line 36: /notebooks/.datacube.conf: Permission denied
jupyter_jupyter_1 exited with code 1
```

Am I missing something here?

I am using Docker 1.12 and Docker Compose 1.8.0 on Debian 9.5 (Stretch) with backports enabled. The only thing I had to change was the version number in `docker-compose.yml`, since Docker Compose 1.8.0 does not support version 3 format, but only version 2.

**Comment by alexgleith** [comment]
Thanks, I'll take a look.

**Comment by alexgleith** [comment]
Hey @ikselven, I've had a quick go at reproducing this, and can't.

Can you delete the file at `notebooks/.datacube.conf` and restart your stack. See what happens then.

Another thing to check is rebuilding the image with `docker-compose build`.

**Comment by ikselven** [comment]
I've got it working now.

The directory `docker-images/jupyter/notebooks` on my host was owned by `root:root` and had permissions 755. It was empty. I changed the owner to `$USER:users` with $USER being the regular user I am working with. After that, I re-ran `sudo docker-compose build` and `sudo docker-compose up`. The permissions error shown above has been gone and there is a `.datacube.conf` in `docker-images/jupyter/notebooks` now.

Having that solved, I hit another issue. When jupyter is launched in the container it showed the following errors:
```python
jupyter_1   | [I 13:06:28.879 NotebookApp] Writing notebook server cookie secret to /notebooks/.local/share/jupyter/runtime/notebook_cookie_secret
jupyter_1   | Traceback (most recent call last):
jupyter_1   |   File "/usr/local/lib/python3.6/dist-packages/traitlets/traitlets.py", line 528, in get
jupyter_1   |     value = obj._trait_values[self.name]
jupyter_1   | KeyError: 'allow_remote_access'
jupyter_1   |
jupyter_1   | During handling of the above exception, another exception occurred:
jupyter_1   |
jupyter_1   | Traceback (most recent call last):
jupyter_1   |   File "/usr/local/lib/python3.6/dist-packages/notebook/notebookapp.py", line 869, in _default_allow_remote
jupyter_1   |     addr = ipaddress.ip_address(self.ip)
jupyter_1   |   File "/usr/lib/python3.6/ipaddress.py", line 54, in ip_address
jupyter_1   |     address)
jupyter_1   | ValueError: '' does not appear to be an IPv4 or IPv6 address
jupyter_1   |
jupyter_1   | During handling of the above exception, another exception occurred:
jupyter_1   |
jupyter_1   | Traceback (most recent call last):
jupyter_1   |   File "/usr/local/bin/jupyter-notebook", line 11, in <module>
jupyter_1   |     sys.exit(main())
jupyter_1   |   File "/usr/local/lib/python3.6/dist-packages/jupyter_core/application.py", line 266, in launch_instance
jupyter_1   |     return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
jupyter_1   |   File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 657, in launch_instance
jupyter_1   |     app.initialize(argv)
jupyter_1   |   File "<decorator-gen-7>", line 2, in initialize
jupyter_1   |   File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
jupyter_1   |     return method(app, *args, **kwargs)
jupyter_1   |   File "/usr/local/lib/python3.6/dist-packages/notebook/notebookapp.py", line 1629, in initialize
jupyter_1   |     self.init_webapp()
jupyter_1   |   File "/usr/local/lib/python3.6/dist-packages/notebook/notebookapp.py", line 1379, in init_webapp
jupyter_1   |     self.jinja_environment_options,
jupyter_1   |   File "/usr/local/lib/python3.6/dist-packages/notebook/notebookapp.py", line 158, in __init__
jupyter_1   |     default_url, settings_overrides, jinja_env_options)
jupyter_1   |   File "/usr/local/lib/python3.6/dist-packages/notebook/notebookapp.py", line 251, in init_settings
jupyter_1   |     allow_remote_access=jupyter_app.allow_remote_access,
jupyter_1   |   File "/usr/local/lib/python3.6/dist-packages/traitlets/traitlets.py", line 556, in __get__
jupyter_1   |     return self.get(obj, cls)
jupyter_1   |   File "/usr/local/lib/python3.6/dist-packages/traitlets/traitlets.py", line 535, in get
jupyter_1   |     value = self._validate(obj, dynamic_default())
jupyter_1   |   File "/usr/local/lib/python3.6/dist-packages/notebook/notebookapp.py", line 872, in _default_allow_remote
jupyter_1   |     for info in socket.getaddrinfo(self.ip, self.port, 0, socket.SOCK_STREAM):
jupyter_1   |   File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
jupyter_1   |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
jupyter_1   | socket.gaierror: [Errno -2] Name or service not known
jupyter_jupyter_1 exited with code 1
```
I configured an explicit IP address in `docker-images/jupyter/docker-compose.yml`, e.g. 0.0.0.0, and it jupyter launches fine without any errors.
